# Generated by Django 3.2.23 on 2024-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0007_auto_20240107_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('icon', models.ImageField(blank=True, upload_to='services/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
