# Generated by Django 3.2.23 on 2024-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0008_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='icon_file',
            field=models.FileField(blank=True, upload_to='services/'),
        ),
    ]
