# Generated by Django 3.2.23 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0009_auto_20240118_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon_file',
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
    ]
