# Generated by Django 3.2.23 on 2024-01-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0011_ourteam_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
    ]
