# Generated by Django 3.2.23 on 2024-01-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0012_ourteam_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
